---
- name: Install latest mysql
  apt: pkg=mysql-server state=latest

- name: Install bits for compiling mysql clients against
  apt: pkg=libmysqlclient-dev

- name: Install efficient zstd compression for backups
  apt: pkg=zstd