---
mitmproxy_secret: "{{ encrypted_mitmproxy_secret }}"
morph_url: https://dev.morph.io
server_name: dev.morph.io
backups: false
cron_jobs: false
github_app_client_id: "{{ encrypted_github_app_client_id }}"
github_app_client_secret: "{{ encrypted_github_app_client_secret }}"
secret_key_base: "{{ encrypted_secret_key_base }}"
sync_auth_token: "{{ encrypted_sync_auth_token }}"
discourse_secret: "{{ encrypted_discourse_secret }}"
cuttlefish_server: cuttlefish.oaf.org.au
cuttlefish_username: "{{ encrypted_cuttlefish_username }}"
cuttlefish_password: "{{ encrypted_cuttlefish_password }}"
stripe_publishable_key: "{{ encrypted_stripe_publishable_key }}"
stripe_secret_key: "{{ encrypted_stripe_secret_key }}"
