---

- name: add elasticsearch key
  apt_key: id=D88E42B4 url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: add elasticsearch repository
  apt_repository: "repo='deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch_version }}/debian stable main' state=present update_cache=yes"

- name: install elasticsearch
  apt: "pkg=elasticsearch state={{ elasticsearch_state }}"

- name: write elasticsearch.yml
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  notify:
    - restart elasticsearch

- name: write logging.yml
  template: "src={{ elasticsearch_logging_template }} dest=/etc/elasticsearch/logging.yml owner=root group=root mode=0644"
  when: elasticsearch_logging_template is defined and elasticsearch_logging_template|length
  notify:
    - restart elasticsearch
