{{ rails_env }}:
  adapter: mysql2
  database: morph{% if rails_env != 'production' %}_{{ rails_env }}{% endif %}
  username: morph
  password: {{ mysql_password }}
  # This is required for sidekiq
  pool: 25
