# Faye
{{ rails_env }}:
  server: "https://faye.{{ server_name }}/faye"
  adapter_javascript_url: "https://faye.{{ server_name }}/faye/faye.js"
  adapter: "Faye"
  auth_token: <%= ENV['SYNC_AUTH_TOKEN'] %>
  async: true
