---
- name: restart nginx
  service: name=nginx state=restarted

- name: Test sudoers and make it live
  shell: visudo -c -f /etc/sudoers.d/deploy.test && cp -f /etc/sudoers.d/deploy.test /etc/sudoers.d/deploy

- name: Restart morph service
  systemd: name=morph.target daemon_reload=yes enabled=yes state=restarted

- name: reload monit
  service: name=monit state=reloaded
