---
github_users:
  - 'br3nda'
  - 'henare'
  - 'ianheggie-oaf'
  - 'jamezpolley'
  - 'mlandauer'
  - 'simonzippy'
ruby_version: "{{ lookup('file', '../.ruby-version') | trim }}"
#python_version: "{{ lookup('file', '../.python-version') | trim }}"
bundler_version: 2.2.33
apt_packages:
  - cmake
  - language-pack-en
  - libffi-dev
  - libgdbm-dev
  - libgmp-dev
  - libncurses5-dev
  - libreadline6-dev
  - libsqlite3-dev
  - libssl-dev
  - libyaml-dev
  - pkg-config
  - ruby-foreman
  - sqlite3
  - zlib1g-dev

bash_alias_lines:
  - "alias cdmorph='if [ \"$USER\" = \"deploy\" ]; then cd /var/www/current; export RAILS_ENV=production; env | egrep RAILS_ENV; else cd /vagrant ; echo \"development. sudo -u deploy -i for production!\"; fi'"
  - 'alias be="bundle exec"'
  - 'alias r="bundle exec rails"'
  - 'alias rk="bundle exec rake"'

backup_gpg_pw: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61643232663363396235343339656666303161663462373838613430623162633162303330666330
          3935373735373930616562653939373933343764666638300a653165393933643337396538313036
          35393033333833653931396333643366393666383233356565383430626364363531336239643438
          6230396532656266660a383335373532633530356562653865373730356465373764373131323236
          38616339636634646563326162626262666632613233646231343366336438383964
backup_target_user: AKIAJBCNWWPWJUFEL7ZQ
backup_target_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36346263326562663438343432393739383365613538376664636634393335636138613465353137
          6131346338326166343636306534636165333035313236340a656535646362666463653535383339
          61303334636232623732333263396130383935333634323766303261636338653363366237613163
          6132336430356264370a396133613563333138613765646265633133666133356638613131663636
          36633564363330363263313533613732376331643266643162626163323539336266636133656234
          3763363366316632356436656661643434313239613731643436

