# Configuration for developing using local vagrant staging server
# Note: this is NOT the code development environment run up using docker compose!
---

rails_env: staging

rvm_users:
  - 'deploy'
  - 'vagrant'
mitmproxy_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30356366333637623738396266653336666330363435343661613465613964373635643137306264
          3464353831336466633835313163303838366339396530310a323630646233663330643662356165
          34353363623035643531346661383263306232303563653962626363623937373337346632373131
          3561326636656663330a646263356464616532623139623438643530666664363430313063336235
          30646566366262376632336532653364666339383362366263613133636561376436
morph_url: https://dev.morph.io
server_name: dev.morph.io
backups: false
cron_jobs: false

# Vagrantfile sets the following from .env:
#   github_app_id, github_app_name, github_app_client_id, github_app_client_secret

secret_key_base: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37633039663663353764376233623932616664666165326461616165643930636663623662383364
          3762303231386566313730353137373339363265316532310a396537613932623461393433393631
          66356232303131326237623230373833333031353736343230306362633261666365616162633065
          6630343334343933380a656431336332323864306263343738346132623238323561653766333930
          62643266646266663966633637653031363838643161653061316165303039353432356661316366
          39643661613065666637313131303463346236383132363231333863353664346166313137636631
          32373939383933643439326133386630333033346538316332343966646431373561333264396334
          64353739393231303932346461336136396433363466316265336361313139636661366664313762
          66663161373739363531343461333131353932323339616466656236383039393137633162373535
          65316133343138386232393862623934626631363233346135306264363538383131326366333664
          636230353738386564326162343637656565
# We don't track development usage
# google_analytics_tracking_id:
# heap_analytics_tracking_id:
sync_auth_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66653662646331613732653262663163336462616665653834336332666334626434366263376639
          6333616438316633646338393033653865623564363062350a383836656463646436326161653836
          32656332376638623961616262663438663730343439306331336234383463653562653238316162
          3232313239333031310a373134646162346535613762623663333430316532393435663865323664
          33323439623265663433393830613463386235613039313038336162346530663837356330326534
          36353737646434396630653230363166303236623333343463633337656165623565396334393639
          38393735376537616364383332396432306162343935376537393061356337666537386234386139
          66393961643935333835

# Vagrantfile sets the following from .env:
# cuttlefish_server, cuttlefish_port, cuttlefish_username, cuttlefish_password

# FIXME: Set to a stripe sandbox! See https://docs.stripe.com/testing
stripe_publishable_key: pk_xxxxxxxxxxxxx
stripe_secret_key: xxxxxxxxxxxxx
discourse_server_name: help.{{ server_name }}
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65623538656438313437343435303533656330313535376338313738616561303265333830383935
          6163346237656562613630346339333935366665383531610a663762316362363939333163343964
          31316332636133343833623465663731626564393431303766333930393561393134306138633739
          6162316630633262650a386565343339323831383561623664626339616264393036386531306635
          39613465343536383665313261353632353263323638663638663237393662653836
newrelic_license_key: null
