---
mitmproxy_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30356366333637623738396266653336666330363435343661613465613964373635643137306264
          3464353831336466633835313163303838366339396530310a323630646233663330643662356165
          34353363623035643531346661383263306232303563653962626363623937373337346632373131
          3561326636656663330a646263356464616532623139623438643530666664363430313063336235
          30646566366262376632336532653364666339383362366263613133636561376436
morph_url: https://dev.morph.io
server_name: dev.morph.io
backups: false
cron_jobs: false
# Need to fill in proper values for github app in development below
github_app_client_id: fe879e7c8951e83fd46b
github_app_client_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62623263343533653065636261333761666265373231633565336266366335396639613634306332
          6461383964613261376666356131653832353334376539630a643165313338653662343830373534
          61363066366338366632343465306464396536623839643236366338356238613537343434366163
          3032663563616531310a353936653162336239386134633264376233313230366462613035633834
          64373833336364643164633064653361333466343338313131393231613261366635663366666632
          3731396536646435353135663338343030323663313664363438
secret_key_base: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37633039663663353764376233623932616664666165326461616165643930636663623662383364
          3762303231386566313730353137373339363265316532310a396537613932623461393433393631
          66356232303131326237623230373833333031353736343230306362633261666365616162633065
          6630343334343933380a656431336332323864306263343738346132623238323561653766333930
          62643266646266663966633637653031363838643161653061316165303039353432356661316366
          39643661613065666637313131303463346236383132363231333863353664346166313137636631
          32373939383933643439326133386630333033346538316332343966646431373561333264396334
          64353739393231303932346461336136396433363466316265336361313139636661366664313762
          66663161373739363531343461333131353932323339616466656236383039393137633162373535
          65316133343138386232393862623934626631363233346135306264363538383131326366333664
          636230353738386564326162343637656565
sync_auth_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66653662646331613732653262663163336462616665653834336332666334626434366263376639
          6333616438316633646338393033653865623564363062350a383836656463646436326161653836
          32656332376638623961616262663438663730343439306331336234383463653562653238316162
          3232313239333031310a373134646162346535613762623663333430316532393435663865323664
          33323439623265663433393830613463386235613039313038336162346530663837356330326534
          36353737646434396630653230363166303236623333343463633337656165623565396334393639
          38393735376537616364383332396432306162343935376537393061356337666537386234386139
          66393961643935333835
discourse_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34353433346633646361666566306539326234316638316533333236376565323234313434323831
          3236326532363730646534653234613137393734663464380a643036363065313663663837333262
          32336337303137656265666361643365373366323231656335363739366636386362656636663361
          3630626133653430310a326136333661323164343963366338623639386434656466383964333166
          32336666386637353362623038363435623161333563636135343966353535383336
cuttlefish_server: cuttlefish.oaf.org.au
cuttlefish_username: morph_2
cuttlefish_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39643265386566346564316363363062663135323830373963663038643864323663356635646537
          3135613662383062306464383131323666336130353034650a666535373336623265386137626461
          33643161343032626563316534326135613766306637613138383030613162616264393537393932
          3533396166313731360a383163376164326336333866306137353534623032313362356661366235
          62616131386237303564376634383630643034333063356133366562373538353738
stripe_publishable_key: pk_test_N1BvejntrSykLCNaxy2QIYls
stripe_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39336462383434333538633134633935633865396635313162353134333466383935366364613861
          6466356639373131306338353335343034653763333166340a303266393566656530313162643538
          32323461373164623936363632303031383037363763363631366232393562383461363638356262
          3363633863383366640a366364613530633737356262626463663038303234633930623630303739
          62333331616434666630653230333065366330633730323961363431366332396133383539326430
          3265346631383764326464326161623735373135613834306338
discourse_server_name: help.{{ server_name }}
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65623538656438313437343435303533656330313535376338313738616561303265333830383935
          6163346237656562613630346339333935366665383531610a663762316362363939333163343964
          31316332636133343833623465663731626564393431303766333930393561393134306138633739
          6162316630633262650a386565343339323831383561623664626339616264393036386531306635
          39613465343536383665313261353632353263323638663638663237393662653836
newrelic_license_key: null
