---

# install

elasticsearch_version: 1.1
elasticsearch_state: present

# elasticsearch.yml

elasticsearch_cluster_name: elasticsearch

elasticsearch_node_name: ~
elasticsearch_node_master: true
elasticsearch_node_data: true
elasticsearch_node_rack: ~
elasticsearch_node_max_local_storage_nodes: ~  # 1

elasticsearch_index_number_of_shards: 5
elasticsearch_index_number_of_replicas: 1

elasticsearch_path_conf: ~
elasticsearch_path_data: ~
elasticsearch_path_work: ~
elasticsearch_path_logs: ~
elasticsearch_path_plugins: ~

elasticsearch_plugin_mandatory: ~

elasticsearch_bootstrap_mlockall: false

elasticsearch_network_bind_host: ~
elasticsearch_network_publish_host: ~
elasticsearch_network_host: "{{ ansible_eth0.ipv4.address }}"
elasticsearch_transport_tcp_port: 9300
elasticsearch_transport_tcp_compress: true
elasticsearch_http_port: 9200
elasticsearch_http_max_content_length: 100mb
elasticsearch_http_enabled: true

elasticsearch_gateway_type: local
elasticsearch_gateway_recover_after_nodes: 1
elasticsearch_gateway_recover_after_time: 5m
elasticsearch_gateway_expected_nodes: 2

elasticsearch_cluster_routing_allocation_node_initial_primaries_recoveries: ~  # 4
elasticsearch_cluster_routing_allocation_node_concurrent_recoveries: ~         # 2
elasticsearch_indices_recovery_max_bytes_per_sec: ~                            # 20mb
elasticsearch_indices_recovery_concurrent_streams: ~                           # 5

elasticsearch_discovery_zen_minimum_master_nodes: ~    # 1
elasticsearch_discovery_zen_ping_timeout: ~            # 3s
elasticsearch_discovery_zen_ping_multicast_enabled: ~  # false
elasticsearch_discovery_zen_ping_unicast_hosts: ~      # "[\"host1\", \"host2:port\"]"

elasticsearch_index_search_slowlog_threshold_query_warn: ~     # 10s
elasticsearch_index_search_slowlog_threshold_query_info: ~     # 5s
elasticsearch_index_search_slowlog_threshold_query_debug: ~    # 2s
elasticsearch_index_search_slowlog_threshold_query_trace: ~    # 500ms
elasticsearch_index_search_slowlog_threshold_fetch_warn: ~     # 1s
elasticsearch_index_search_slowlog_threshold_fetch_info: ~     # 800ms
elasticsearch_index_search_slowlog_threshold_fetch_debug: ~    # 500ms
elasticsearch_index_search_slowlog_threshold_fetch_trace: ~    # 200ms
elasticsearch_index_indexing_slowlog_threshold_index_warn: ~   # 10s
elasticsearch_index_indexing_slowlog_threshold_index_info: ~   # 5s
elasticsearch_index_indexing_slowlog_threshold_index_debug: ~  # 2s
elasticsearch_index_indexing_slowlog_threshold_index_trace: ~  # 500ms

monitor_jvm_gc_young_warn: ~   # 1000ms
monitor_jvm_gc_young_info: ~   # 700ms
monitor_jvm_gc_young_debug: ~  # 400ms
monitor_jvm_gc_old_warn: ~     # 10s
monitor_jvm_gc_old_info: ~     # 5s
monitor_jvm_gc_old_debug: ~    # 2s

# logging.yml

elasticsearch_logging_template: logging.yml.j2
